# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the SGI SN (Altix) device drivers.
#

obj-$(CONFIG_MSPEC)			+= mspec.o
obj-$(CONFIG_SGI_IOC4)			+= ioc4.o
obj-$(CONFIG_SGI_SNSC)			+= snsc.o snsc_event.o
obj-$(CONFIG_SGI_MBCS)			+= mbcs.o
obj-$(CONFIG_AGP_SGI_TIOCA)		+= sgi-agp.o

#
